### ISSUE TITLE
MDC-101 JAVA: MaterialButton bug

### ISSUE THREAD

**Issue by dkvirus** [material-components/material-components-android-codelabs#27]
**Describe the bug**

I follow the mdn-101 course for Java.On the official website => [this](https://codelabs.developers.google.com/codelabs/mdc-101-java/#3)。

The button component is used as follows, but the error is reported all the time. I'm looking at Google for reasons, and it only works properly when the `android:textAppearance` attribute is added.

```
<android.support.design.button.MaterialButton
       android:id="@+id/next_button"
       android:layout_width="wrap_content"
       android:layout_height="wrap_content"
       android:layout_alignParentEnd="true"
       android:layout_alignParentRight="true"
       android:text="@string/shr_button_next" />
```

**Comment by wcshi** [comment]
What error is being reported? What's theme are you using?

**Comment by dkvirus** [comment]
@wcshi sorry, i miss that.

res > layout > login.xml :  There is no `textAppearance` attribute. An error will be reported.

```
<android.support.design.button.MaterialButton
                android:id="@+id/next_button"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignParentEnd="true"
                android:layout_alignParentRight="true"
                android:text="Next" />
```

error info: 

```
2018-11-21 08:58:49.315 20558-20558/top.dkvirus.novel E/AndroidRuntime: FATAL EXCEPTION: main
    Process: top.dkvirus.novel, PID: 20558
    android.view.InflateException: Binary XML file line #69: Binary XML file line #69: Error inflating class android.support.design.button.MaterialButton
    Caused by: android.view.InflateException: Binary XML file line #69: Error inflating class android.support.design.button.MaterialButton
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at top.dkvirus.novel.fragment.LoginFragment.onCreateView(LoginFragment.java:23)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
        at android.app.Activity.performStart(Activity.java:7157)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2937)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalArgumentException: This component requires that you specify a valid TextAppearance attribute. Update your app theme to inherit from Theme.MaterialComponents (or a descendant).
        at android.support.design.internal.ThemeEnforcement.checkTextAppearance(ThemeEnforcement.java:170)
2018-11-21 08:58:49.316 20558-20558/top.dkvirus.novel E/AndroidRuntime:     at android.support.design.internal.ThemeEnforcement.obtainStyledAttributes(ThemeEnforcement.java:75)
        at android.support.design.button.MaterialButton.<init>(MaterialButton.java:140)
        at android.support.design.button.MaterialButton.<init>(MaterialButton.java:133)
        	... 42 more
```

It won't work until I add the textAppearance attribute

```
<android.support.design.button.MaterialButton
                android:id="@+id/next_button"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignParentEnd="true"
                android:layout_alignParentRight="true"
     ==>        android:textAppearance="?android:attr/textAppearanceLargeInverse"
                android:text="Next" />
```

**Comment by wcshi** [comment]
This is working as intended. Please "update your app theme to inherit from Theme.MaterialComponents (or a descendant)"

>  Caused by: java.lang.IllegalArgumentException: This component requires that you specify a valid TextAppearance attribute. Update your app theme to inherit from Theme.MaterialComponents (or a descendant).
        at android.support.design.internal.ThemeEnforcement.checkTextAppearance(ThemeEnforcement.java:170)
>

**Comment by A86S** [comment]
I have same issue with Material Button due to `android:textAllCaps="true"`   i removed this line and everything works fine.
